import type { Metadata } from "next";
import "./globals.css";
import { Inter } from "next/font/google";
import { AppSidebar } from "@/components/app-sidebar";
import { cn } from "@/lib/utils";
import { ThemeProvider } from "@/components/theme-provider"
import { CommandDialogDemo } from "@/components/command-dialog";


const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Link-Eats",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body
        className={cn("min-h-screen bg-background font-sans antialiased", inter.className)}
      >


<ThemeProvider
            attribute="class"
            defaultTheme="system"
            enableSystem
            disableTransitionOnChange
          >
        
            <AppSidebar>{children}</AppSidebar>
            <CommandDialogDemo/>

            </ThemeProvider>
        
      </body>
    </html>
  );
}