import type { Metadata } from "next";
import "./globals.css";
import {Inter} from "next/font/google"
import { AppSidebar } from "@/components/app-sidebar"
import { cn } from "@/lib/utils";

const inter = Inter({subsets: ["latin"]})

export const metadata: Metadata = {
  title: "Link-Eats",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
      className={cn(" min-h-screen bg-background font-sans antialiased",inter.className)}
      >
      
      <AppSidebar />
      <main>
        {children}
      </main>
   
      </body>
    </html>
  );
}
